name: 👷 hexo deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: ⬇️ checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: ⬇️ setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 16

      - name: 👷 setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "xqyjlj@126.com"
          git config --global user.name "xqyjlj"
          npm install hexo-cli -g
          npm install
          npm install hexo-deployer-git --save

      - name: ⬆️ deploy
        run: |
          hexo clean
          hexo deploy
